# Generated by Django 4.1.1 on 2023-08-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='aciklama',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
