# Generated by Django 4.1.1 on 2023-08-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='video',
            new_name='deneme',
        ),
    ]
